# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）docker-compose
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        # skopeo copy docker://quay.io/coreos/etcd:v3.5.5 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/etcd:v3.5.5
        # skopeo copy docker://docker.io/minio/minio:RELEASE.2023-03-20T20-16-18Z docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/minio:RELEASE.2023-03-20T20-16-18Z
        # skopeo copy docker://docker.io/milvusdb/milvus:v2.4.5 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/milvus:v2.4.5
        # skopeo copy docker://docker.io/zilliz/attu:v2.3.10 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/attu:v2.3.10
        # skopeo copy docker://docker.io/milvusdb/milvus:v2.4.5-gpu docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/milvus:v2.4.5-gpu
        # skopeo copy docker://docker.io/rabbitmq docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/rabbitmq
        # skopeo copy docker://docker.io/python:3.10-slim docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/python:3.10-slim
        # skopeo copy docker://docker.io/milvusdb/milvus:v2.4.8 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/milvus:v2.4.8
        # skopeo copy docker://docker.io/python:3.10 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/python:3.10
        # skopeo copy docker://docker.io/willfarrell/autoheal docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/autoheal
        # skopeo copy docker://docker.io/elasticsearch:8.15.0 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/elasticsearch:8.15.0
        # skopeo copy docker://docker.io/kibana:8.15.0 docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/kibana:8.15.0
        # skopeo copy docker://docker.io/clash-lan/clash:latest docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/clash-lan/clash:latest
        # skopeo copy docker://docker.io/searxng/searxng docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/searxng/searxng
        skopeo copy docker://docker.io/portainer/portainer-ce:alpine docker://registry.cn-hangzhou.aliyuncs.com/lvdun-images/portainer/portainer-ce:alpine
